/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  product_card,
} from './global/class/ionCard';


export namespace Components {
  interface AppHome {
    'Cards': any;
  }
  interface AppRoot {}
  interface SecondK {
    'Cards': product_card;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes {
    'Cards'?: any;
  }
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface SecondK extends JSXBase.HTMLAttributes {
    'Cards'?: product_card;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'second-k': SecondK;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {

  // Adding a global JSX for backcompatibility with legacy dependencies
  export namespace JSX {
    export interface Element {}
  }



  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLSecondKElement extends Components.SecondK, HTMLStencilElement {}
  var HTMLSecondKElement: {
    prototype: HTMLSecondKElement;
    new (): HTMLSecondKElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'second-k': HTMLSecondKElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

