/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  SideBar,
} from './models/admin-models/sidebarModel';


export namespace Components {
  interface AddPost {}
  interface AdminPage {
    'current_item': number;
    'nav_items': SideBar[];
  }
  interface CardPage {
    'patients': any[];
  }
  interface TopNavBar {
    'head': string;
  }
}

declare global {


  interface HTMLAddPostElement extends Components.AddPost, HTMLStencilElement {}
  var HTMLAddPostElement: {
    prototype: HTMLAddPostElement;
    new (): HTMLAddPostElement;
  };

  interface HTMLAdminPageElement extends Components.AdminPage, HTMLStencilElement {}
  var HTMLAdminPageElement: {
    prototype: HTMLAdminPageElement;
    new (): HTMLAdminPageElement;
  };

  interface HTMLCardPageElement extends Components.CardPage, HTMLStencilElement {}
  var HTMLCardPageElement: {
    prototype: HTMLCardPageElement;
    new (): HTMLCardPageElement;
  };

  interface HTMLTopNavBarElement extends Components.TopNavBar, HTMLStencilElement {}
  var HTMLTopNavBarElement: {
    prototype: HTMLTopNavBarElement;
    new (): HTMLTopNavBarElement;
  };
  interface HTMLElementTagNameMap {
    'add-post': HTMLAddPostElement;
    'admin-page': HTMLAdminPageElement;
    'card-page': HTMLCardPageElement;
    'top-nav-bar': HTMLTopNavBarElement;
  }
}

declare namespace LocalJSX {
  interface AddPost extends JSXBase.HTMLAttributes<HTMLAddPostElement> {}
  interface AdminPage extends JSXBase.HTMLAttributes<HTMLAdminPageElement> {
    'current_item'?: number;
    'nav_items'?: SideBar[];
  }
  interface CardPage extends JSXBase.HTMLAttributes<HTMLCardPageElement> {
    'patients'?: any[];
  }
  interface TopNavBar extends JSXBase.HTMLAttributes<HTMLTopNavBarElement> {
    'head'?: string;
  }

  interface IntrinsicElements {
    'add-post': AddPost;
    'admin-page': AdminPage;
    'card-page': CardPage;
    'top-nav-bar': TopNavBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


