/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  SideBar,
} from './models/admin-models/sidebarModel';


export namespace Components {
  interface AdminPage {
    'current_item': number;
    'nav_items': SideBar[];
  }
  interface IconPage {}
}

declare global {


  interface HTMLAdminPageElement extends Components.AdminPage, HTMLStencilElement {}
  var HTMLAdminPageElement: {
    prototype: HTMLAdminPageElement;
    new (): HTMLAdminPageElement;
  };

  interface HTMLIconPageElement extends Components.IconPage, HTMLStencilElement {}
  var HTMLIconPageElement: {
    prototype: HTMLIconPageElement;
    new (): HTMLIconPageElement;
  };
  interface HTMLElementTagNameMap {
    'admin-page': HTMLAdminPageElement;
    'icon-page': HTMLIconPageElement;
  }
}

declare namespace LocalJSX {
  interface AdminPage extends JSXBase.HTMLAttributes<HTMLAdminPageElement> {
    'current_item'?: number;
    'nav_items'?: SideBar[];
  }
  interface IconPage extends JSXBase.HTMLAttributes<HTMLIconPageElement> {}

  interface IntrinsicElements {
    'admin-page': AdminPage;
    'icon-page': IconPage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


